# fly.toml file generated for crimson-wildflower-1711 on 2021-09-17T00:18:57-07:00

app = "crimson-wildflower-1711"

kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]
  auto_rollback = false
  PORT = 8080

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 500
    soft_limit = 250
    type = "requests"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
    method = "get"
    path = "/"
    protocol = "tcp"
    [services.tcp_checks.headers]
